create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 16),
  grid_size integer not null check (grid_size in (3, 4, 5)),
  mode text not null default 'challenge' check (mode in ('challenge')),
  image_key text not null check (char_length(image_key) between 1 and 32),
  time_seconds integer not null check (time_seconds >= 0 and time_seconds <= 86400),
  steps integer not null check (steps > 0 and steps <= 100000),
  created_at timestamptz not null default now()
);

alter table public.scores enable row level security;

drop policy if exists "Scores are publicly readable" on public.scores;
create policy "Scores are publicly readable"
on public.scores
for select
to anon
using (true);

drop policy if exists "Anyone can submit challenge scores" on public.scores;
create policy "Anyone can submit challenge scores"
on public.scores
for insert
to anon
with check (mode = 'challenge');

create index if not exists scores_rank_idx
on public.scores (grid_size, time_seconds asc, steps asc, created_at asc);
